### ISSUE TITLE
[FEATURE] Create docker-compose config

### ISSUE THREAD

**Issue by chaoticbear** [burningmantech/ranger-ims-server#1166]
# Overview

Goal is to create a docker compose config for standardized / faster developer on-boarding, and consistent environments.

## Goals

Can be addressed in multiple PRs.

### Pending in #1163

 - [x] Setup environment in just a few steps 
    -  (eg. copy files, edit options, docker compose up ...) 
 - [x] No local packages or services depended on (nodejs, python, mysql, etc)
 - [x] Organize docker files in `docker` directory 
 - [x] Add `README` steps for development 
 - [x] Compatible networking with `ranger-ims-web` docker compose setup see: https://github.com/burningmantech/ranger-ims-web/issues/1039
 
### TODO

 - [ ] Add `caddy` reverse proxy with `ims.lvh.me` domain or similar
 - [ ] Add ability to run linters & tests from compose commands

**Comment by chaoticbear** [comment]
Closing because the remaining tasks here aren't deal-breakers and can be created as separate issues if needed in the future.
